name: BuildIOSApp

on:

jobs:
  - name: BuildArchive
    run: |
      xcodebuild \
        -workspace iosApp/iosApp.xcworkspace \
        -scheme iosApp \
        -sdk iphoneos \
        -configuration Release \
        archive \
        -archivePath build/iosApp.xcarchive

  - name: Export IPA
    run: |
      xcodebuild \
        -exportArchive \
        -archivePath build/iosApp.xcarchive \
        -exportOptionsPlist iosApp/exportOptions.plist \
        -exportPath build/ipa
