name: BuildIOSApp

on:
  workflow_dispatch: # allows manual trigger


jobs:
 build-ios:
    runs-on: macos-latest
    steps:
    
      - uses: actions/checkout@v4
      
      - name: BuildArchive
        run: |
          xcodebuild \
            -workspace iosApp/iosApp.xcworkspace \
            -scheme iosApp \
            -sdk iphoneos \
            -configuration Release \
            archive \
            -archivePath build/iosApp.xcarchive
    
      - name: Export IPA
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath build/iosApp.xcarchive \
            -exportOptionsPlist iosApp/exportOptions.plist \
            -exportPath build/ipa
            
      - uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ipa/*.ipa
