name: Build iOS XCFramework

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Build XCFramework
        run: ./gradlew :shared:assembleXCFramework
      - name: Upload framework
        uses: actions/upload-artifact@v4
        with:
          name: ios-xcframework
          path: shared/build/XCFrameworks/
