name: Build IOS

on:
  push:
    branches: [main]
  workflow_dispatch: # allows manual trigger


jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: List Gradle Tasks
        run: ./gradlew :composeApp:tasks --all

      - name: Build XCFramework
    
        run: ./gradlew :composeApp:assembleXCFramework

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-framework
          path: composeApp/build/XCFrameworks/
