name: Build KMP Project

on:
  push:
    branches: [main]
  workflow_dispatch: # allows manual trigger


jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build XCFramework
        run: ./gradlew :shared:assembleXCFramework

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-framework
          path: shared/build/XCFrameworks/
