name: Build All

on:
  push:
    branches: [main]
  workflow_dispatch: # allows manual trigger


jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
        
      - name: Build XCFramework
        run: ./gradlew :composeApp:assembleDebugXCFramework \
         -PdisableParallelIosBuild=true --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-framework
          path: composeApp/build/XCFrameworks/
