name: Build iOS

on:
  workflow_dispatch:   # allows manual trigger
  push:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build iOS XCFramework
        run: ./gradlew :shared:assembleXCFramework

      - name: Archive XCFramework
        uses: actions/upload-artifact@v4
        with:
          name: ios-framework
          path: shared/build/XCFrameworks/
